clc;
clear;
close all;
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Jun-2015 14:42:18

% Create figure
figure1 = figure;

X1 = -10:2:6;
YMatrix1 = [-0.73407391	-0.897555855	-1.188142334	-1.189282642	-1.322791803
-1.143999072	-1.394766356	-2.017323591	-2.269391609	-2.428499053
-1.908329844	-2.48153489	-3.661471487	-3.935912535	-4.071709045
-3.121308207	-4.319976624	-5.156492585	-5.64384874	-5.636340705
-4.817008641	-5.748436195	-6.743942629	-6.681430246	-6.969663673
-5.818282451	-6.759766705	-7.543424173	-7.797036289	-8.005676254
-6.264389967	-7.405515356	-8.356240394	-8.816701456	-8.965583458
-6.789351365	-7.977928616	-9.108323874	-9.484205088	-9.779458965
-6.919266537	-8.269282676	-9.824934152	-10.13237047	-10.01143806
];

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Color',[1 0 0],'Parent',axes1);
set(plot1(1),'DisplayName','1-bit','Marker','o','LineStyle','--');
set(plot1(2),'DisplayName','2-bit','Marker','square','LineStyle','--');
set(plot1(3),'DisplayName','3-bit','Marker','diamond','LineStyle','-.');
set(plot1(4),'DisplayName','4-bit','Marker','v','LineStyle','-.');
% set(plot1(5),'DisplayName','5-bit','Marker','^','LineStyle','-.');
% set(plot1(6),'DisplayName','6-bit','Marker','>','LineStyle','--');
% set(plot1(7),'DisplayName','7-bit','Marker','<','LineStyle','-.');
% set(plot1(8),'DisplayName','8-bit','Marker','x','LineStyle','--');
set(plot1(5),'DisplayName','+\infty','Color',[0 0 0]);

% Create xlabel
xlabel('SNR (dB)','Margin',2,'FontSize',12);

% Create ylabel
ylabel('Normalized MSE','Margin',2,'FontSize',12);
title('WLAN, N_t=16, N_r=16, N_s=2')
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[0 0 0],'Location','best');


%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Jun-2015 14:42:18

% Create figure
figure1 = figure;

X1 = -10:2:6;
YMatrix1 = [2.173886462	2.329469899	2.805686678	3.000140037	2.977523255
2.823050397	3.31360254	3.650328339	3.877086808	3.917442972
3.604208776	3.967898188	4.281630576	4.40798977	4.513513373
4.029401167	4.507786792	5.024674023	5.040381718	5.203665335
4.528922071	5.076421828	5.64595563	5.890307173	6.083396946
5.119001797	5.590938737	6.427492657	6.745705963	6.779879634
5.698332988	6.337002502	7.315277829	7.614046995	7.758329059
6.455660439	6.710474715	7.927050843	8.459619856	8.610983318
6.919469172	7.246976323	8.610352207	9.356663906	9.714315937
];

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Color',[1 0 0],'Parent',axes1);
set(plot1(1),'DisplayName','1-bit','Marker','o','LineStyle','--');
set(plot1(2),'DisplayName','2-bit','Marker','square','LineStyle','--');
set(plot1(3),'DisplayName','3-bit','Marker','diamond','LineStyle','-.');
set(plot1(4),'DisplayName','4-bit','Marker','v','LineStyle','-.');
% set(plot1(5),'DisplayName','5-bit','Marker','^','LineStyle','-.');
% set(plot1(6),'DisplayName','6-bit','Marker','>','LineStyle','--');
% set(plot1(7),'DisplayName','7-bit','Marker','<','LineStyle','-.');
% set(plot1(8),'DisplayName','8-bit','Marker','x','LineStyle','--');
set(plot1(5),'DisplayName','+\infty','Color',[0 0 0]);

% Create xlabel
xlabel('SNR (dB)','Margin',2,'FontSize',12);

% Create ylabel
ylabel('Rate (bps/Hz)','Margin',2,'FontSize',12);
% title('Hybrid Precoding, N_t=16, N_r=4, N_s=2');
title('WLAN, N_t=16, N_r=4')

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[0 0 0],'Location','best');

